version: '3'

services: 
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    volumes: ['./db_data:/var/lib/mysql']
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite

networks:
  wpsite:
